toolchain/BUILD.tpl: add missing ':ar' dependency (#28)
In bazel versions before 1.0, `:ar` files are needed in the linker
components. The breaking change was made in 2200d531.

When linking a static library, the following error could occur:

```
ERROR: BUILD.bazel:123:1: Linking of rule '//foo:libfoo' failed (Exit 1)
external/io_bazel/src/main/tools/process-wrapper-legacy.cc:58: "execvp(external/llvm_toolchain/bin/llvm-ar, ...)": No such file or directory
```

We should support bazel versions less than 1.0 until we start
depending on features from newer releases more seriously.

Signed-off-by: Jason S. McMullan <jason.mcmullan@uber.com>