Fix: make standard library headers includable from modules (#851)
When you try to include stdlib headers in a module, you end up with an
error like this:

```
INFO: Analyzed target //src/tmp:tmp (0 packages loaded, 0 targets configured).
ERROR: /home/dev/.cache/bazel/_bazel_dev/081ca399a9bd900129a8f87351cbba8a/external/+std_module+std_module/BUILD.bazel:5:11: Deps scanning for std.cppm failed: (Exit 1): process-wrapper failed: error executing CppDepsScanning command 
  (cd /home/dev/.cache/bazel/_bazel_dev/081ca399a9bd900129a8f87351cbba8a/sandbox/processwrapper-sandbox/4/execroot/_main && \
  exec env - \
    DEPS_SCANNER_OUTPUT_FILE=bazel-out/k8-fastbuild/bin/external/+std_module+std_module/_objs/std/std.pic.ddi \
    PATH=/bin:/usr/bin:/usr/local/bin \
    PWD=/proc/self/cwd \
    TMPDIR=/tmp \
  /home/dev/.cache/bazel/_bazel_dev/install/3e6f3b7d6fdac67aed908160850e082b/process-wrapper '--timeout=0' '--kill_delay=15' '--stats=/home/dev/.cache/bazel/_bazel_dev/081ca399a9bd900129a8f87351cbba8a/sandbox/processwrapper-sandbox/4/stats.out' external/toolchains_llvm++llvm+llvm_toolchain/bin/cpp_module_deps_scanner.sh -U_FORTIFY_SOURCE '--target=x86_64-unknown-linux-gnu' -U_FORTIFY_SOURCE -fstack-protector -fno-omit-frame-pointer -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -Bexternal/toolchains_llvm++llvm+llvm_toolchain_llvm/bin/ -resource-dir external/toolchains_llvm++llvm+llvm_toolchain_llvm/lib/clang/23 '-std=c++17' -MD -MF bazel-out/k8-fastbuild/bin/external/+std_module+std_module/_objs/std/std.pic.ddi.d '-frandom-seed=bazel-out/k8-fastbuild/bin/external/+std_module+std_module/_objs/std/std.pic.ddi' -iquote external/+std_module+std_module -iquote bazel-out/k8-fastbuild/bin/external/+std_module+std_module '-std=c++26' -Wno-reserved-module-identifier -c external/+std_module+std_module/std.cppm -o bazel-out/k8-fastbuild/bin/external/+std_module+std_module/_objs/std/std.pic.ddi -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -Xclang -fmodule-file-home-is-cwd -Xclang -fbuiltin-headers-in-system-modules -Xclang -fmodules-embed-all-files)
Diagnostics while scanning dependencies for 'external/+std_module+std_module/std.cppm':
external/+std_module+std_module/std.cppm:16:10: fatal error: '__config' file not found
Target //src/tmp:tmp failed to build
```

This is because the `cpp_module_deps_scanning` action doesn't get the
`_nomsan_cxx_args` applied to it, which is what passes `-cxx-isystem`
pointing to libc++. So `clang-scan-deps` was failing immediately when
trying to include stdlib headers. Making the args apply to the
module-related actions (same ones already listed for
`_relocatable_cpp_modules_args`) fixes it.

This was assisted by AI (Gemini).

---------

Signed-off-by: Richard Dong <66289396+rdong8@users.noreply.github.com>